aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "27:ef:f9:ef:31:23:77:68:8f:f7:b3:01:47:54:67:38"
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "bot@circleci.com"
            cd website && yarn install && USE_SSH=true yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-master