name: documentation
permissions:
      id-token: write
      contents: read

on:
  push:
    branches: [master]
  schedule:
    - cron: '5 4 1 1 *'

jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: eu-west-1
          
      - name: Copy files to s3 and clear cache
        run: |
          cd website && yarn install && yarn run build
          cd build
          aws s3 sync . s3://sykes.technology
          aws cloudfront create-invalidation \
            --distribution-id E1WOSL0TMLZN7 \
            --paths "/*"


